
ARDUINO_DIR  = /usr/share/arduino/

TARGET       = MPU-6050
ARDUINO_LIBS =  Servo Wire Wire/utility



# BOARD_TAG    = mega2560
# ARDUINO_PORT = /dev/ttyACM0

# BOARD_TAG    = uno

BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB0





include $(ARDUINO_DIR)/Arduino.mk
