###############################################################################
#   @file makefile
#   @brief  makefile for test_DFRobotPowerShield test project.
#
#   This Arduino project is a test for the DFRobotPowerShield class.
#
#   @author GOM
#   @date   2014-02-13  Thu.    17:42:25    Creation.
###############################################################################

ARDUINO_DIR  = /usr/share/arduino/

TARGET       =  test_DFRobotPowerShield
ARDUINO_LIBS =  Wire Wire/utility


BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0



include $(ARDUINO_DIR)/Arduino.mk
