
ARDUINO_DIR  = /usr/share/arduino/

TARGET       = test_Sparkfun_fuelGauge
ARDUINO_LIBS =  Wire Wire/utility

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0
# BOARD_TAG    = nano328
# ARDUINO_PORT = /dev/ttyUSB0


include $(ARDUINO_DIR)/Arduino.mk


