
ARDUINO_DIR  = /usr/share/arduino/

TARGET       = test_Adafruit_PWMServoDriver
ARDUINO_LIBS =  Wire Wire/utility

BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB0


include $(ARDUINO_DIR)/Arduino.mk
