ArduParts: MAX1704 Class Reference
MAX1704 Class Reference
#include <MAX1704.h>
Public Member Functions
float stateOfCharge ()
void showConfig ()
void reset ()
void quickStart ()
char version ()
void setAlertThreshold (uint8_t level)
int alertThreshold ()
boolean isSleeping ()
boolean isAlerting ()
void sleep ()
void awake ()
Private Member Functions
void performCommand (byte address, int value)
void readFrom (byte address, byte &msb, byte &lsb)
Detailed Description
Definition at line 33 of file MAX1704.h.
Member Function Documentation
int MAX1704::alertThreshold ()
Definition at line 86 of file MAX1704.cpp.
References MAX1704_CONFIG, and readFrom().
void MAX1704::awake ()
Definition at line 123 of file MAX1704.cpp.
boolean MAX1704::isAlerting ()
Definition at line 97 of file MAX1704.cpp.
References MAX1704_CONFIG, and readFrom().
boolean MAX1704::isSleeping ()
Definition at line 108 of file MAX1704.cpp.
References MAX1704_CONFIG, readFrom(), and sleep().
void MAX1704::performCommand (byte address, int value) [private]
Definition at line 128 of file MAX1704.cpp.
References MAX1704_ADDR, and MAX1704_COMMAND.
void MAX1704::quickStart ()
Definition at line 59 of file MAX1704.cpp.
References MAX1704_QUICK_START, and performCommand().
void MAX1704::readFrom (byte address, byte & msb, byte & lsb) [private]
Definition at line 137 of file MAX1704.cpp.
References MAX1704_ADDR.
void MAX1704::reset ()
Definition at line 54 of file MAX1704.cpp.
References MAX1704_POWER_ON_RESET, and performCommand().
void MAX1704::setAlertThreshold (uint8_t level)
Definition at line 77 of file MAX1704.cpp.
References MAX1704_ADDR, MAX1704_ALERT_LEVEL, and MAX1704_CONFIG.
void MAX1704::showConfig ()
Definition at line 36 of file MAX1704.cpp.
References alertThreshold(), isAlerting(), isSleeping(), sleep(), and version().
void MAX1704::sleep ()
Definition at line 119 of file MAX1704.cpp.
float MAX1704::stateOfCharge ()
Definition at line 23 of file MAX1704.cpp.
References MAX1704_SOC, and readFrom().
char MAX1704::version ()
Definition at line 64 of file MAX1704.cpp.
References MAX1704_VERSION, and readFrom().
The documentation for this class was generated from the following files:
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MAX1704/MAX1704.h
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MAX1704/MAX1704.cpp