ArduParts: Mpu6050 Class Reference
Mpu6050 Class Reference
#include <Mpu6050.h>
Classes
union accel_t_gyro_union
Public Member Functions
Mpu6050 ()
bool init (String *argErrorString=0)
uint8_t whoAmI (void) const
void clearData (void)
bool updateData (void)
int16_t rawAccelX (void) const
int16_t rawAccelY (void) const
int16_t rawAccelZ (void) const
int16_t rawGyroX (void) const
int16_t rawGyroY (void) const
int16_t rawGyroZ (void) const
int16_t rawTemperature (void) const
double accelX_g (void) const
double accelY_g (void) const
double accelZ_g (void) const
double gyroX_deg_s (void) const
double gyroY_deg_s (void) const
double gyroZ_deg_s (void) const
double temperature_celsius (void) const
double angleX_deg (void) const
double angleY_deg (void) const
double angleZ_deg (void) const
Private Types
enum AccelerometerRange { AccelerometerRange_2g = 0, AccelerometerRange_4g = 1, AccelerometerRange_8g = 2, AccelerometerRange_16g = 3 }
enum GyroRange { GyroRange250deg_s = 0, GyroRange500deg_s = 1, GyroRange1000deg_s = 2, GyroRange2000deg_s = 3 }
Private Member Functions
int accelerometerCountsPerG (void) const
accelerometerCountsPerG Returns the constant corresponding to the number of "counts" there is in a G depending on the accelerometer's range.
float gyroscopeCountsPerDeg_s (void) const
gyroscopeCountsPerDeg_s Returns the constant corresponding to the number of "counts" there is in a deg/s depending on the gyroscope's range.
int read (int start, uint8_t *buffer, int size)
read is a common function to read multiple bytes from an I2C device.
int write (int start, const uint8_t *pData, int size)
int write_reg (int reg, uint8_t data)
Private Attributes
AccelerometerRange m_accelerometerRange
accel_t_gyro_union m_data
double m_forceVector
GyroRange m_gyroRange
uint8_t m_whoAmI
Detailed Description
Definition at line 8 of file Mpu6050.h.
Member Enumeration Documentation
enum Mpu6050::AccelerometerRange [private]
Enumerator:
AccelerometerRange_2g
AccelerometerRange_4g
AccelerometerRange_8g
AccelerometerRange_16g
Definition at line 53 of file Mpu6050.h.
enum Mpu6050::GyroRange [private]
Enumerator:
GyroRange250deg_s
GyroRange500deg_s
GyroRange1000deg_s
GyroRange2000deg_s
Definition at line 60 of file Mpu6050.h.
Constructor & Destructor Documentation
Mpu6050::Mpu6050 ()
Definition at line 601 of file Mpu6050.cpp.
Member Function Documentation
int Mpu6050::accelerometerCountsPerG (void) const [private]
accelerometerCountsPerG Returns the constant corresponding to the number of "counts" there is in a G depending on the accelerometer's range.
Returns:
Definition at line 611 of file Mpu6050.cpp.
References AccelerometerRange_16g, AccelerometerRange_2g, AccelerometerRange_4g, AccelerometerRange_8g, and m_accelerometerRange.
double Mpu6050::accelX_g (void) const
Definition at line 641 of file Mpu6050.cpp.
References accelerometerCountsPerG(), and rawAccelX().
double Mpu6050::accelY_g (void) const
Definition at line 646 of file Mpu6050.cpp.
References accelerometerCountsPerG(), and rawAccelY().
double Mpu6050::accelZ_g (void) const
Definition at line 651 of file Mpu6050.cpp.
References accelerometerCountsPerG(), and rawAccelZ().
double Mpu6050::angleX_deg (void) const
Definition at line 656 of file Mpu6050.cpp.
References accelX_g(), C_RAD_TO_DEG, and m_forceVector.
double Mpu6050::angleY_deg (void) const
Definition at line 661 of file Mpu6050.cpp.
References accelY_g(), C_RAD_TO_DEG, and m_forceVector.
double Mpu6050::angleZ_deg (void) const
Definition at line 666 of file Mpu6050.cpp.
References accelZ_g(), C_RAD_TO_DEG, and m_forceVector.
void Mpu6050::clearData (void)
Definition at line 671 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::temperature, Mpu6050::accel_t_gyro_union::value, Mpu6050::accel_t_gyro_union::x_accel, Mpu6050::accel_t_gyro_union::x_gyro, Mpu6050::accel_t_gyro_union::y_accel, Mpu6050::accel_t_gyro_union::y_gyro, Mpu6050::accel_t_gyro_union::z_accel, and Mpu6050::accel_t_gyro_union::z_gyro.
float Mpu6050::gyroscopeCountsPerDeg_s (void) const [private]
gyroscopeCountsPerDeg_s Returns the constant corresponding to the number of "counts" there is in a deg/s depending on the gyroscope's range.
Returns:
Definition at line 684 of file Mpu6050.cpp.
References GyroRange1000deg_s, GyroRange2000deg_s, GyroRange250deg_s, GyroRange500deg_s, and m_gyroRange.
double Mpu6050::gyroX_deg_s (void) const
Definition at line 714 of file Mpu6050.cpp.
References gyroscopeCountsPerDeg_s(), and rawGyroX().
double Mpu6050::gyroY_deg_s (void) const
Definition at line 719 of file Mpu6050.cpp.
References gyroscopeCountsPerDeg_s(), and rawGyroY().
double Mpu6050::gyroZ_deg_s (void) const
Definition at line 724 of file Mpu6050.cpp.
References gyroscopeCountsPerDeg_s(), and rawGyroZ().
bool Mpu6050::init (String * argErrorString = 0)
Definition at line 729 of file Mpu6050.cpp.
References AccelerometerRange_16g, AccelerometerRange_2g, AccelerometerRange_4g, AccelerometerRange_8g, GyroRange1000deg_s, GyroRange2000deg_s, GyroRange250deg_s, GyroRange500deg_s, LOGLN, m_accelerometerRange, m_gyroRange, m_whoAmI, MPU6050_ACCEL_CONFIG, MPU6050_AFS_SEL_16G, MPU6050_AFS_SEL_2G, MPU6050_AFS_SEL_4G, MPU6050_AFS_SEL_8G, MPU6050_FS_SEL_1000, MPU6050_FS_SEL_2000, MPU6050_FS_SEL_250, MPU6050_FS_SEL_500, MPU6050_GYRO_CONFIG, MPU6050_PWR_MGMT_1, MPU6050_PWR_MGMT_2, MPU6050_WHO_AM_I, read(), and write_reg().
int16_t Mpu6050::rawAccelX (void) const
Definition at line 823 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::x_accel.
int16_t Mpu6050::rawAccelY (void) const
Definition at line 828 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::y_accel.
int16_t Mpu6050::rawAccelZ (void) const
Definition at line 833 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::z_accel.
int16_t Mpu6050::rawGyroX (void) const
Definition at line 838 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::x_gyro.
int16_t Mpu6050::rawGyroY (void) const
Definition at line 843 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::y_gyro.
int16_t Mpu6050::rawGyroZ (void) const
Definition at line 848 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::value, and Mpu6050::accel_t_gyro_union::z_gyro.
int16_t Mpu6050::rawTemperature (void) const
Definition at line 853 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::temperature, and Mpu6050::accel_t_gyro_union::value.
int Mpu6050::read (int start, uint8_t * buffer, int size) [private]
read is a common function to read multiple bytes from an I2C device.
Parameters:
start
buffer
size
Returns:
It uses the boolean parameter for Wire.endTransMission() to be able to hold or release the I2C-bus. This is implemented in Arduino 1.0.1. Only this function is used to read. There is no function for a single byte.
Definition at line 858 of file Mpu6050.cpp.
References MPU6050_I2C_ADDRESS.
double Mpu6050::temperature_celsius (void) const
Definition at line 888 of file Mpu6050.cpp.
References m_data, Mpu6050::accel_t_gyro_union::temperature, and Mpu6050::accel_t_gyro_union::value.
bool Mpu6050::updateData (void)
Definition at line 899 of file Mpu6050.cpp.
References accelX_g(), accelY_g(), accelZ_g(), clearData(), m_data, m_forceVector, MPU6050_ACCEL_XOUT_H, read(), and SWAP.
uint8_t Mpu6050::whoAmI (void) const
Definition at line 946 of file Mpu6050.cpp.
References m_whoAmI.
int Mpu6050::write (int start, const uint8_t * pData, int size) [private]
Definition at line 951 of file Mpu6050.cpp.
References MPU6050_I2C_ADDRESS.
int Mpu6050::write_reg (int reg, uint8_t data) [private]
Definition at line 972 of file Mpu6050.cpp.
References write().
Member Data Documentation
AccelerometerRange Mpu6050::m_accelerometerRange [private]
Definition at line 109 of file Mpu6050.h.
accel_t_gyro_union Mpu6050::m_data [private]
Definition at line 110 of file Mpu6050.h.
double Mpu6050::m_forceVector [private]
Definition at line 111 of file Mpu6050.h.
GyroRange Mpu6050::m_gyroRange [private]
Definition at line 112 of file Mpu6050.h.
uint8_t Mpu6050::m_whoAmI [private]
Definition at line 113 of file Mpu6050.h.
The documentation for this class was generated from the following files:
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MPU6050/Mpu6050.h
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MPU6050/Mpu6050.cpp