ArduParts: Adafruit_BMP180 Class Reference
Adafruit_BMP180 Class Reference
Interface for Adafruit's BMP180 sensor board.
#include <Adafruit_BMP180.h>
Classes
struct CalibrationData
Public Types
enum ErrorCode { ErrorUnknown = -1, NoError = 0, ErrorBadChipId }
enum Bmp180Mode { ModeUltraLowPower = 0, ModeStandard = 1, ModeHighResolution = 2, ModeUltraHighResolution = 3 }
Public Member Functions
Adafruit_BMP180 ()
ErrorCode init (Bmp180Mode argMode=ModeUltraHighResolution)
float getAltitude_m (float argSeaLevelPressure_Pa=101525)
float getPressure_Pa (void)
float getTemperature_c (void)
int32_t readRawPressure (void)
int32_t readRawTemperature (void)
Private Member Functions
void readCalibrationData (void)
Static Private Member Functions
static void read_int16 (byte argRegister, int16_t *argValue)
static void read_uint8 (byte argRegister, uint8_t *argValue)
static void read_uint16 (byte argRegister, uint16_t *argValue)
static void writeCommand (byte argRegister, byte argValue)
Private Attributes
CalibrationData m_calibrationData
Bmp180Mode m_mode
Detailed Description
Interface for Adafruit's BMP180 sensor board.
This class and its implementation is mostly based on Kevin Townsend's work for Adafruit Industries (Adafruit_BMP085_Unified class).
See also:
http://www.adafruit.com/products/1603#Technical_Details
http://learn.adafruit.com/bmp085/wiring-the-bmp085
Author:
GOM © 2014 GOM
Date:
2014-02-20 Thu. 15:03:00 Creation.
Definition at line 20 of file Adafruit_BMP180.h.
Member Enumeration Documentation
enum Adafruit_BMP180::Bmp180Mode
Enumerator:
ModeUltraLowPower
Todo:
test this
ModeStandard
Todo:
test this
ModeHighResolution
Todo:
test this
ModeUltraHighResolution
Definition at line 31 of file Adafruit_BMP180.h.
enum Adafruit_BMP180::ErrorCode
Enumerator:
ErrorUnknown
NoError
ErrorBadChipId
Definition at line 25 of file Adafruit_BMP180.h.
Constructor & Destructor Documentation
Adafruit_BMP180::Adafruit_BMP180 ()
Definition at line 44 of file Adafruit_BMP180.cpp.
Member Function Documentation
float Adafruit_BMP180::getAltitude_m (float argSeaLevelPressure_Pa = 101525)
Definition at line 54 of file Adafruit_BMP180.cpp.
References getPressure_Pa(), and getTemperature_c().
float Adafruit_BMP180::getPressure_Pa (void)
Definition at line 76 of file Adafruit_BMP180.cpp.
References Adafruit_BMP180::CalibrationData::ac1, Adafruit_BMP180::CalibrationData::ac2, Adafruit_BMP180::CalibrationData::ac3, Adafruit_BMP180::CalibrationData::ac4, Adafruit_BMP180::CalibrationData::ac5, Adafruit_BMP180::CalibrationData::ac6, Adafruit_BMP180::CalibrationData::b1, Adafruit_BMP180::CalibrationData::b2, m_calibrationData, m_mode, Adafruit_BMP180::CalibrationData::mc, Adafruit_BMP180::CalibrationData::md, readRawPressure(), and readRawTemperature().
float Adafruit_BMP180::getTemperature_c (void)
Definition at line 127 of file Adafruit_BMP180.cpp.
References Adafruit_BMP180::CalibrationData::ac5, Adafruit_BMP180::CalibrationData::ac6, m_calibrationData, Adafruit_BMP180::CalibrationData::mc, Adafruit_BMP180::CalibrationData::md, and readRawTemperature().
Adafruit_BMP180::ErrorCode Adafruit_BMP180::init (Bmp180Mode argMode = ModeUltraHighResolution)
Definition at line 152 of file Adafruit_BMP180.cpp.
References BMP180_CHIP_ID, BMP180_REGISTER_CHIPID, ErrorBadChipId, m_mode, NoError, read_uint8(), and readCalibrationData().
void Adafruit_BMP180::read_int16 (byte argRegister, int16_t * argValue) [static, private]
Definition at line 259 of file Adafruit_BMP180.cpp.
References read_uint16().
void Adafruit_BMP180::read_uint16 (byte argRegister, uint16_t * argValue) [static, private]
Definition at line 293 of file Adafruit_BMP180.cpp.
References AdafruitBmp180_Address.
void Adafruit_BMP180::read_uint8 (byte argRegister, uint8_t * argValue) [static, private]
Definition at line 271 of file Adafruit_BMP180.cpp.
References AdafruitBmp180_Address.
void Adafruit_BMP180::readCalibrationData (void) [private]
Definition at line 180 of file Adafruit_BMP180.cpp.
References Adafruit_BMP180::CalibrationData::ac1, Adafruit_BMP180::CalibrationData::ac2, Adafruit_BMP180::CalibrationData::ac3, Adafruit_BMP180::CalibrationData::ac4, Adafruit_BMP180::CalibrationData::ac5, Adafruit_BMP180::CalibrationData::ac6, Adafruit_BMP180::CalibrationData::b1, Adafruit_BMP180::CalibrationData::b2, BMP180_REGISTER_CAL_AC1, BMP180_REGISTER_CAL_AC2, BMP180_REGISTER_CAL_AC3, BMP180_REGISTER_CAL_AC4, BMP180_REGISTER_CAL_AC5, BMP180_REGISTER_CAL_AC6, BMP180_REGISTER_CAL_B1, BMP180_REGISTER_CAL_B2, BMP180_REGISTER_CAL_MB, BMP180_REGISTER_CAL_MC, BMP180_REGISTER_CAL_MD, m_calibrationData, Adafruit_BMP180::CalibrationData::mb, Adafruit_BMP180::CalibrationData::mc, Adafruit_BMP180::CalibrationData::md, read_int16(), and read_uint16().
int32_t Adafruit_BMP180::readRawPressure (void)
Definition at line 198 of file Adafruit_BMP180.cpp.
References BMP180_REGISTER_CONTROL, BMP180_REGISTER_PRESSUREDATA, BMP180_REGISTER_READPRESSURECMD, m_mode, ModeHighResolution, ModeStandard, ModeUltraHighResolution, ModeUltraLowPower, read_uint16(), read_uint8(), and writeCommand().
int32_t Adafruit_BMP180::readRawTemperature (void)
Definition at line 241 of file Adafruit_BMP180.cpp.
References BMP180_REGISTER_CONTROL, BMP180_REGISTER_READTEMPCMD, BMP180_REGISTER_TEMPDATA, read_uint16(), and writeCommand().
void Adafruit_BMP180::writeCommand (byte argRegister, byte argValue) [static, private]
Definition at line 315 of file Adafruit_BMP180.cpp.
References AdafruitBmp180_Address.
Member Data Documentation
CalibrationData Adafruit_BMP180::m_calibrationData [private]
Definition at line 73 of file Adafruit_BMP180.h.
Bmp180Mode Adafruit_BMP180::m_mode [private]
Definition at line 74 of file Adafruit_BMP180.h.
The documentation for this class was generated from the following files:
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/BMP180/Adafruit_BMP180.h
/home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/BMP180/Adafruit_BMP180.cpp