ArduParts: /home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MAX1704/test_Sparkfun_fuelGauge.cpp File Reference
test_Sparkfun_fuelGauge.cpp File Reference
#include "test_Sparkfun_fuelGauge.h"
#include "Arduino.h"
#include <Wire.h>
#include "MAX1704.h"
Functions
void setup ()
void loop ()
Variables
MAX1704 sensor
Function Documentation
void loop ()
Definition at line 48 of file test_Sparkfun_fuelGauge.cpp.
References MAX1704::stateOfCharge().
void setup ()
Definition at line 10 of file test_Sparkfun_fuelGauge.cpp.
References MAX1704::quickStart(), MAX1704::reset(), and MAX1704::showConfig().
Variable Documentation
MAX1704 sensor
Definition at line 8 of file test_Sparkfun_fuelGauge.cpp.