ArduParts: /home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/MPU6050/test_Mpu6050_main.cpp File Reference
test_Mpu6050_main.cpp File Reference
#include "test_Mpu6050_main.h"
#include "Arduino.h"
#include "Mpu6050.h"
#include <Servo.h>
Classes
struct CartesianCoordinates
Defines
#define VERBOSE
A commenter pour desactiver log.
#define PRINT_ACCEL_RAW
Commenter pour desactiver affichage des valeurs "brutes" de l'accelerometre.
#define PRINT_ACCEL_G
Commenter pour desactiver affichage des valeurs en G de l'accelerometre.
#define PRINT_CALCULATED_ANGLES
Commenter pour desactiver affichage des valeurs de l'inclinaison calculée à partir de l'acceleration.
#define PRINT_GYRO_RAW
Commenter pour desactiver affichage des valeurs "brutes" du gyroscope.
#define PRINT_GYRO_DEG_PER_S
Commenter pour desactiver affichage des valeurs en degres par seconde du gyroscope.
#define PRINT_TEMPERATURE
Commenter pour desactiver affichage de la temperature.
#define LOG(msg) Serial.print(msg)
#define LOGLN(msg) Serial.println(msg)
Functions
void setup ()
void loop ()
Variables
static const double C_DEG_TO_RAD = 0.017453293
static const double C_RAD_TO_DEG = 57.295779506
Mpu6050 sensor
Define Documentation
#define LOG (msg) Serial.print(msg)
Definition at line 22 of file test_Mpu6050_main.cpp.
#define LOGLN (msg) Serial.println(msg)
Definition at line 23 of file test_Mpu6050_main.cpp.
#define PRINT_ACCEL_G
Commenter pour desactiver affichage des valeurs en G de l'accelerometre.
Definition at line 13 of file test_Mpu6050_main.cpp.
#define PRINT_ACCEL_RAW
Commenter pour desactiver affichage des valeurs "brutes" de l'accelerometre.
Definition at line 12 of file test_Mpu6050_main.cpp.
#define PRINT_CALCULATED_ANGLES
Commenter pour desactiver affichage des valeurs de l'inclinaison calculée à partir de l'acceleration.
Definition at line 14 of file test_Mpu6050_main.cpp.
#define PRINT_GYRO_DEG_PER_S
Commenter pour desactiver affichage des valeurs en degres par seconde du gyroscope.
Definition at line 16 of file test_Mpu6050_main.cpp.
#define PRINT_GYRO_RAW
Commenter pour desactiver affichage des valeurs "brutes" du gyroscope.
Definition at line 15 of file test_Mpu6050_main.cpp.
#define PRINT_TEMPERATURE
Commenter pour desactiver affichage de la temperature.
Definition at line 17 of file test_Mpu6050_main.cpp.
#define VERBOSE
A commenter pour desactiver log.
Definition at line 11 of file test_Mpu6050_main.cpp.
Function Documentation
void loop ()
< ce return permet de sortir de la fonction loop; cette fonction etant integree dans une boucle infinie, elle sera immediatement rappelee.
Definition at line 82 of file test_Mpu6050_main.cpp.
References Mpu6050::accelX_g(), Mpu6050::accelY_g(), Mpu6050::accelZ_g(), Mpu6050::angleX_deg(), Mpu6050::angleY_deg(), Mpu6050::angleZ_deg(), Mpu6050::gyroX_deg_s(), Mpu6050::gyroY_deg_s(), Mpu6050::gyroZ_deg_s(), LOG, LOGLN, Mpu6050::rawAccelX(), Mpu6050::rawAccelY(), Mpu6050::rawAccelZ(), Mpu6050::temperature_celsius(), and Mpu6050::updateData().
void setup ()
Definition at line 50 of file test_Mpu6050_main.cpp.
References Mpu6050::init(), LOG, LOGLN, and Mpu6050::whoAmI().
Variable Documentation
const double C_DEG_TO_RAD = 0.017453293 [static]
Definition at line 42 of file test_Mpu6050_main.cpp.
const double C_RAD_TO_DEG = 57.295779506 [static]
Definition at line 43 of file test_Mpu6050_main.cpp.
Mpu6050 sensor
Definition at line 45 of file test_Mpu6050_main.cpp.