ArduParts: /home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/DFRobotPowerShield/test_DFRobotPowerShield.cpp File Reference
test_DFRobotPowerShield.cpp File Reference
#include "test_DFRobotPowerShield.h"
#include "Arduino.h"
#include "DFRobotPowerShield.h"
Functions
void setup ()
void loop ()
Variables
DFRobotPowerShield powerShield
static const char CHAR_FRAME_BEGIN = '$'
static const char CHAR_FRAME_END = '*'
static const char CHAR_FRAME_FIELDSEPARATOR = ';'
Function Documentation
void loop ()
Definition at line 27 of file test_DFRobotPowerShield.cpp.
References CHAR_FRAME_BEGIN, CHAR_FRAME_END, CHAR_FRAME_FIELDSEPARATOR, DFRobotPowerShield::outputEnabled(), and DFRobotPowerShield::voltage().
void setup ()
Definition at line 12 of file test_DFRobotPowerShield.cpp.
References DFRobotPowerShield::setOutputEnabled().
Variable Documentation
const char CHAR_FRAME_BEGIN = '$' [static]
Definition at line 8 of file test_DFRobotPowerShield.cpp.
const char CHAR_FRAME_END = '*' [static]
Definition at line 9 of file test_DFRobotPowerShield.cpp.
const char CHAR_FRAME_FIELDSEPARATOR = ';' [static]
Definition at line 10 of file test_DFRobotPowerShield.cpp.
DFRobotPowerShield powerShield
Definition at line 6 of file test_DFRobotPowerShield.cpp.