ArduParts: /home/user/Programmation/arduino/sourceforge/arduParts/arduParts-git/PCA9685/test_PCA9685.cpp File Reference
test_PCA9685.cpp File Reference
#include "test_PCA9685.h"
#include "Arduino.h"
#include "PCA9685.h"
Functions
void pca9685_printConfig (PCA9685 &argController)
void setup ()
void loop ()
Variables
PCA9685 controller
Function Documentation
void loop ()
< ce return permet de sortir de la fonction loop; cette fonction etant integree dans une boucle infinie, elle sera immediatement rappelee.
Definition at line 284 of file test_PCA9685.cpp.
References Adafruit_BMP180::getAltitude_m(), Adafruit_BMP180::getPressure_Pa(), Adafruit_BMP180::getTemperature_c(), PCA9685::isSleeping(), PCA9685::OUTPUT_COUNT, pca9685_printConfig(), Adafruit_BMP180::readRawPressure(), Adafruit_BMP180::readRawTemperature(), PCA9685::setOutput(), and PCA9685::setSleeping().
void pca9685_printConfig (PCA9685 & argController)
Definition at line 16 of file test_PCA9685.cpp.
References PCA9685::address(), PCA9685::canRestart(), PCA9685::ChangeOnAcknowledge, PCA9685::ChangeOnStop, PCA9685::clockFrequency(), PCA9685::disabledOutputPolicy(), PCA9685::isSleeping(), PCA9685::isUsingExternalClock(), PCA9685::ledAllCallAddressEnabled(), PCA9685::outputChangeEvent(), PCA9685::OutputFalse, PCA9685::outputFrequency(), PCA9685::OutputHighImpedance, PCA9685::outputStateInverted(), PCA9685::outputStructure(), PCA9685::OutputStructureOpenDrain, PCA9685::OutputStructureTotemPole, PCA9685::OutputTrue, PCA9685::subAddress1Enabled(), PCA9685::subAddress2Enabled(), and PCA9685::subAddress3Enabled().
void setup ()
Definition at line 125 of file test_PCA9685.cpp.
References PCA9685::address(), PCA9685::canRestart(), PCA9685::ChangeOnAcknowledge, PCA9685::ChangeOnStop, PCA9685::clockFrequency(), PCA9685::disabledOutputPolicy(), PCA9685::init(), Adafruit_BMP180::init(), PCA9685::isSleeping(), PCA9685::isUsingExternalClock(), PCA9685::ledAllCallAddressEnabled(), Adafruit_BMP180::NoError, PCA9685::outputChangeEvent(), PCA9685::OutputFalse, PCA9685::outputFrequency(), PCA9685::OutputHighImpedance, PCA9685::outputStateInverted(), PCA9685::outputStructure(), PCA9685::OutputStructureOpenDrain, PCA9685::OutputStructureTotemPole, PCA9685::OutputTrue, PCA9685::reset(), PCA9685::restart(), PCA9685::setDisabledOutputPolicy(), PCA9685::setOutputFrequency(), PCA9685::setSleeping(), PCA9685::subAddress1Enabled(), PCA9685::subAddress2Enabled(), and PCA9685::subAddress3Enabled().
Variable Documentation
PCA9685 controller
Definition at line 11 of file test_PCA9685.cpp.