ArduParts: PCA9685 Class Reference
PCA9685 Class Reference
The PCA9685 class provides an interface for Arduino devices to access NXP's PCA9685 16-channel, 12-bit PWM Fm+ I2C-bus LED controller.
#include <PCA9685.h>
Public Types
enum OutputChangeEvent { ChangeOnStop = 0, ChangeOnAcknowledge }
The OutputChangeEvent enum represents the different events on which the output will be changed.
enum OutputPolicyWhenDisabled { OutputFalse = 0, OutputTrue = 1, OutputHighImpedance = 2 }
The OutputPolicyWhenDisabled enum represents the diffenrent ways to manage outputs behaviour when the /OE pin is set to logical 1 (output disabled).
enum OutputStructure { OutputStructureOpenDrain = 0, OutputStructureTotemPole = 1 }
The OutputStructure enum represents the different ways to manage output's internal ("electronic") structure.
Public Member Functions
PCA9685 (uint8_t argAddress=DEFAULT_ADDRESS, double argClockFrequency=DEFAULT_CLOCKFREQUENCY_HZ)
Constructor; sets needed parameters.
void init (void)
Sets up the initial conditions to let the device work.
void reset (void)
Sends a Software Reset Call (SWRST Call) command on the I2C bus.
bool isSleeping (void)
Returns the the device's power mode.
void setSleeping (bool argIsSleeping)
Sets the device's power mode.
bool canRestart (void)
To know whether the device can be restored from a previous state, for example after the device has been put to sleep.
bool restart (void)
Wakes up the device and restarts all of the previously active PWM channels if any.
double clockFrequency (void) const
Returns the value that has been set by the constructor.
bool isUsingExternalClock (void)
To know whether the internal counter is using internal clock source (oscillator) or external clock (EXTCLK pin).
void setUseExternalClock (void)
To use an external clock source instead of the internal one.
uint8_t address (void) const
Returns the value that has been set by the constructor.
bool subAddress1Enabled (void)
void setSubAddress1Enabled (bool argEnabled)
bool subAddress2Enabled (void)
void setSubAddress2Enabled (bool argEnabled)
bool subAddress3Enabled (void)
void setSubAddress3Enabled (bool argEnabled)
bool ledAllCallAddressEnabled (void)
void setLedAllCallAddressEnabled (bool argEnabled)
To set whether the device will answer to "Led All Call" address.
double outputFrequency (void)
Returns the PWM output frequency, calculated from the chip's clock prescaler and the PCA9685::m_clockFrequency.
bool setOutputFrequency (double argFrequency_Hz)
Calculates then sets internal counter's prescale value to let the output's frequency be as close as possible to argFrequency_Hz.
uint8_t outputPrescale (void)
To get the value of the prescale that will be used to divide internal counter's input clock. Sets the output frequency.
void setOutputPrescale (uint8_t argPrescale)
To set the value of the prescale that will be used to divide internal counter's input clock.
bool outputStateInverted (void)
To know whether the output logical state is inverted or not.
void setOutputStateInverted (bool argInverted)
To set wether the output's logical state is inverted or not. Applicable when /OE pin==0.
OutputChangeEvent outputChangeEvent (void)
Returns the event type on which the output will be changed.
void setOutputChangeEvent (OutputChangeEvent argEvent)
To set the event type on which the output will be changed.
OutputStructure outputStructure (void)
To get the output driver's internal structure type.
void setOutputStructure (OutputStructure argStructure)
To set the output driver's internal structure type.
OutputPolicyWhenDisabled disabledOutputPolicy (void)
Returns the PCA9685's outputs state of when its /OE pin is set to logical 1 (==output disabled).
void setDisabledOutputPolicy (OutputPolicyWhenDisabled argPolicy)
To set the PCA9685's outputs state for when the /OE pin is set to logical 1 (==device's output disabled).
bool setOutput_const (uint8_t argOutputNbr, bool argEnabled)
To set argOutputNbr to be always ON/OFF depending on argEnabled.
int8_t setOutput_pwm (uint8_t argOutputNbr, uint16_t argOn, uint16_t argOff)
To set the cycle & phase of an output.
bool outputIsForcedFullOn (uint8_t argOutputNbr)
To know whether output argOutputNbr is forced "full ON" or not.
bool setOutputForceFullOn (uint8_t argOutputNbr, bool argForceFullOn)
To enable/disable the forcing of output argOutputNbr to be always fully on.
bool outputIsForcedFullOff (uint8_t argOutputNbr)
To know whether output argOutputNbr is forced "full OFF" or not.
bool setOutputForceFullOff (uint8_t argOutputNbr, bool argForceFullOff)
To enable/disable the forcing of output argOutputNbr to be always fully off.
Static Public Attributes
static const uint8_t DEFAULT_ADDRESS = 0x40
The default address of the device when all bits [A0;A5] are set to logic 0.
static const float DEFAULT_CLOCKFREQUENCY_HZ = 25000000
The default clock frequency for internal counter. PCA9685's internal oscillator runs at 25MHz.
static const uint8_t OUTPUT_COUNT = 16
The number of outputs the PCA9685 have.
Protected Member Functions
uint8_t read_8u (const uint8_t &argAddress)
Convenience function to read a 8-bits unisgned data from the register argAddress of the device at address PCA9685::m_address.
void write_8u (const uint8_t &argAddress, const uint8_t &argData)
Convenience function to write a 8-bits unisgned argData into the register argAddress of the device at address PCA9685::m_address.
bool isAutoIncrementingRegister (void)
Returns whether the device will auto-increment registers number (when multiple-read/write) or not.
void setAutoIncrementRegister (bool argEnableAutoIncrement)
To set whether the device will auto-increment registers number (when multiple-read/write) or not.
Protected Attributes
const uint8_t m_address
The PCA9685's I2C slave address, as set by the constructor.
const double m_clockFrequency
The clock frequency, to calculate prescales; set by the constructor.
Detailed Description
The PCA9685 class provides an interface for Arduino devices to access NXP's PCA9685 16-channel, 12-bit PWM Fm+ I2C-bus LED controller.
Author
GOM
Copyright
Copyright © 2014 GOM - X11 License
Definition at line 42 of file PCA9685.h.
Member Enumeration Documentation
enum PCA9685::OutputChangeEvent
The OutputChangeEvent enum represents the different events on which the output will be changed.
Default: ChangeOnStop
Enumerator:
ChangeOnStop
Outputs change on STOP command. Allows synchronizing outputs of more than one PCA9685. Applicable to registers from 06h (LED0_ON_L) to 45h (LED15_OFF_H) only. One or more registers can be written, in any order, before STOP.
ChangeOnAcknowledge
Update on ACK requires all 4 PWM channel registers to be loaded before outputs will change on the last ACK.
Definition at line 64 of file PCA9685.h.
enum PCA9685::OutputPolicyWhenDisabled
The OutputPolicyWhenDisabled enum represents the diffenrent ways to manage outputs behaviour when the /OE pin is set to logical 1 (output disabled).
Enumerator:
OutputFalse
When /OE pin=1, outputs will be set to logical 0.
OutputTrue
When /OE pin=1 (output drivers not enabled), outputs will be set to logical 1.
OutputHighImpedance
When /OE pin=1 (output drivers not enabled), outputs will be set to high impedance.
Definition at line 81 of file PCA9685.h.
enum PCA9685::OutputStructure
The OutputStructure enum represents the different ways to manage output's internal ("electronic") structure.
Normal LEDs can be driven directly in either mode. Some newer LEDs include integrated Zener diodes to limit voltage transients, reduce EMI, protect the LEDs and these must be driven only in the open-drain mode to prevent overheating the IC.
Enumerator:
OutputStructureOpenDrain
The 16 LEDn outputs are configured with an open-drain structure.
OutputStructureTotemPole
The 16 LEDn outputs are configured with a totem pole structure. Allows minimizing the amount of external components required to control the external driver (N-type or P-type device).
Definition at line 103 of file PCA9685.h.
Constructor & Destructor Documentation
PCA9685::PCA9685 (uint8_t argAddress = DEFAULT_ADDRESS, double argClockFrequency = DEFAULT_CLOCKFREQUENCY_HZ)
Constructor; sets needed parameters.
Parameters
argAddress The address of the PCA9685.
Range: [0x40;0x7F].
argClockFrequency The clock frequency of the device counter.
argAddress is set to PCA9685::DEFAULT_ADDRESS by default, but it will depend on the hardware. See datasheet for details.
argClockFrequency is not absolutely needed to communicate with the device, it is used for some of this class' methods to perform operations such as calculation of the prescaler when setting output frequency with PCA9685::setOutputFrequency() or, the opposite way, to calculate the output's frequency from the read prescale value. If using the internal oscillator, frequency is 25MHz (set in PCA9685::DEFAULT_CLOCKFREQUENCY_HZ); otherwise it shall be set to the external clock frequency. See datasheet for applyable range.
Definition at line 237 of file PCA9685.cpp.
Member Function Documentation
uint8_t PCA9685::address (void) const
Returns the value that has been set by the constructor.
To get the address that is used to communicate with the PCA9685. Set by constructor.
Returns
The device's address.
Definition at line 251 of file PCA9685.cpp.
References m_address.
Referenced by pca9685_printConfig(), and setup().
bool PCA9685::canRestart (void)
To know whether the device can be restored from a previous state, for example after the device has been put to sleep.
Returns
true if the device can be "restarted".
false if no previous state can be restored.
Note
Conditions that could make the device not to be restored:
Power cycle
I2C software reset command
If the MODE2 OCH bit is logic 0, write to any PWM register then issue an I2C-bus STOP.
If the MODE2 OCH bit is logic 1, write to all four PWM registers in any PWM channel.
Definition at line 273 of file PCA9685.cpp.
References MASK_MODE1_RESTART, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), restart(), and setup().
double PCA9685::clockFrequency (void) const
Returns the value that has been set by the constructor.
Returns the frequency of the clock as set by the constructor.
Returns
The frequency of the clock (Hertz).
Definition at line 307 of file PCA9685.cpp.
References m_clockFrequency.
Referenced by outputFrequency(), pca9685_printConfig(), setOutputFrequency(), and setup().
PCA9685::OutputPolicyWhenDisabled PCA9685::disabledOutputPolicy (void)
Returns the PCA9685's outputs state of when its /OE pin is set to logical 1 (==output disabled).
Returns
a value from the PCA9685::OutputPolicyWhenDisabled enum.
Definition at line 285 of file PCA9685.cpp.
References MASK_MODE2_OUTNE0, MASK_MODE2_OUTNE1, OutputFalse, OutputHighImpedance, OutputTrue, read_8u(), and REG_MODE2.
Referenced by pca9685_printConfig(), and setup().
void PCA9685::init (void)
Sets up the initial conditions to let the device work.
Begins Wire (I2C interface) and resets the device.
Definition at line 319 of file PCA9685.cpp.
References reset().
Referenced by setup().
bool PCA9685::isAutoIncrementingRegister (void) protected
Returns whether the device will auto-increment registers number (when multiple-read/write) or not.
Returns
true if auto-increment of register number is enabled;
false if auto-increment is disabled.
Definition at line 334 of file PCA9685.cpp.
References MASK_MODE1_AI, read_8u(), and REG_MODE1.
bool PCA9685::isSleeping (void)
Returns the the device's power mode.
Returns
true if the device is in low-power mode (internal oscillator off);
false if the device is in normal mode.
Definition at line 347 of file PCA9685.cpp.
References MASK_MODE1_SLEEP, read_8u(), and REG_MODE1.
Referenced by loop(), pca9685_printConfig(), setOutputPrescale(), and setup().
bool PCA9685::isUsingExternalClock (void)
To know whether the internal counter is using internal clock source (oscillator) or external clock (EXTCLK pin).
Returns the MODE1_EXTCLK bit state.
Returns
true if the device is using external clock input.
false if the device is using internal oscillator as clock source.
See Also
PCA9685::setUseExternalClock()
Definition at line 366 of file PCA9685.cpp.
References MASK_MODE1_EXTCLK, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), and setup().
bool PCA9685::ledAllCallAddressEnabled (void)
Returns
true if the device will answer to Led All Call address;
false otherwise.
Definition at line 378 of file PCA9685.cpp.
References MASK_MODE1_ALLCALL, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), and setup().
PCA9685::OutputChangeEvent PCA9685::outputChangeEvent (void)
Returns the event type on which the output will be changed.
Returns
See Also
PCA9685::OutputChangeEvent
Definition at line 392 of file PCA9685.cpp.
References ChangeOnAcknowledge, ChangeOnStop, MASK_MODE2_OCH, read_8u(), and REG_MODE2.
Referenced by pca9685_printConfig(), and setup().
double PCA9685::outputFrequency (void)
Returns the PWM output frequency, calculated from the chip's clock prescaler and the PCA9685::m_clockFrequency.
Where:
= PCA9685::clockFrequency()
= PCA9685::outputPrescale()
See Also
PCA9685::setOutputFrequency()
Definition at line 416 of file PCA9685.cpp.
References clockFrequency(), and outputPrescale().
Referenced by pca9685_printConfig(), and setup().
bool PCA9685::outputIsForcedFullOff (uint8_t argOutputNbr)
To know whether output argOutputNbr is forced "full OFF" or not.
Parameters
argOutputNbr The output to be checked
Returns
true if the output is forced disabled (no PWM);
false if the output is not forced disabled.
See Also
PCA9685::outputIsForcedFullOn()
Definition at line 432 of file PCA9685.cpp.
References MASK_LEDn_OFF_H_FULLOFF, read_8u(), and REG_LED0_OFF_H.
Referenced by pca9685_printConfig().
bool PCA9685::outputIsForcedFullOn (uint8_t argOutputNbr)
To know whether output argOutputNbr is forced "full ON" or not.
Attention
The output can be forced enabled and not working because by default the output is forced disabled and the LEDn_OFF_H_FULLOFF bit ("full 0FF") overrides the LEDn_ON_H_FULLON bit ("full ON").
Parameters
argOutputNbr The output to be checked
Returns
true if the output is forced enabled (no PWM);
false if the output is not forced enabled.
See Also
PCA9685::outputIsForcedFullOff()
Definition at line 455 of file PCA9685.cpp.
References MASK_LEDn_ON_H_FULLON, read_8u(), and REG_LED0_ON_H.
Referenced by pca9685_printConfig().
uint8_t PCA9685::outputPrescale (void)
To get the value of the prescale that will be used to divide internal counter's input clock. Sets the output frequency.
Returns
An uint8_t containing the prescale value.
Definition at line 471 of file PCA9685.cpp.
References read_8u(), and REG_PRE_SCALE.
Referenced by outputFrequency().
bool PCA9685::outputStateInverted (void)
To know whether the output logical state is inverted or not.
Returns
true if output logical state is inverted.
false otherwise.
Definition at line 483 of file PCA9685.cpp.
References MASK_MODE2_INVRT, read_8u(), and REG_MODE2.
Referenced by pca9685_printConfig(), and setup().
PCA9685::OutputStructure PCA9685::outputStructure (void)
To get the output driver's internal structure type.
Returns
Definition at line 495 of file PCA9685.cpp.
References MASK_MODE2_OUTDRV, OutputStructureOpenDrain, OutputStructureTotemPole, read_8u(), and REG_MODE2.
Referenced by pca9685_printConfig(), and setup().
uint8_t PCA9685::read_8u (const uint8_t & argAddress) protected
Convenience function to read a 8-bits unisgned data from the register argAddress of the device at address PCA9685::m_address.
Parameters
argAddress The uint8_t address of the register we want to read.
Returns
An uint8_t containing the read byte.
Definition at line 513 of file PCA9685.cpp.
References CMD_READ, and m_address.
Referenced by canRestart(), disabledOutputPolicy(), isAutoIncrementingRegister(), isSleeping(), isUsingExternalClock(), ledAllCallAddressEnabled(), outputChangeEvent(), outputIsForcedFullOff(), outputIsForcedFullOn(), outputPrescale(), outputStateInverted(), outputStructure(), restart(), setAutoIncrementRegister(), setDisabledOutputPolicy(), setLedAllCallAddressEnabled(), setOutputChangeEvent(), setOutputForceFullOff(), setOutputForceFullOn(), setOutputStateInverted(), setOutputStructure(), setSleeping(), setSubAddress1Enabled(), setSubAddress2Enabled(), setSubAddress3Enabled(), setUseExternalClock(), subAddress1Enabled(), subAddress2Enabled(), and subAddress3Enabled().
void PCA9685::reset (void)
Sends a Software Reset Call (SWRST Call) command on the I2C bus.
Warning
May interfere with other devices - it looks like a standard I2C command...
Definition at line 531 of file PCA9685.cpp.
References CMD_SOFTWARE_RESET.
Referenced by init(), and setup().
bool PCA9685::restart (void)
Wakes up the device and restarts all of the previously active PWM channels if any.
Returns
false If the device can't restart (see PCA9685::canRestart() for more details);
true otherwise.
See Also
PCA9685::canRestart()
Definition at line 550 of file PCA9685.cpp.
References canRestart(), M_BIT_SET, MASK_MODE1_RESTART, read_8u(), REG_MODE1, setSleeping(), and write_8u().
Referenced by setup().
void PCA9685::setAutoIncrementRegister (bool argEnableAutoIncrement) protected
To set whether the device will auto-increment registers number (when multiple-read/write) or not.
Parameters
argEnableAutoIncrement
true : Auto-increment will be enabled;
false : Auto-increment will be disabled.
Definition at line 615 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_AI, read_8u(), REG_MODE1, and write_8u().
void PCA9685::setDisabledOutputPolicy (OutputPolicyWhenDisabled argPolicy)
To set the PCA9685's outputs state for when the /OE pin is set to logical 1 (==device's output disabled).
Parameters
argPolicy The policy to be set.
See Also
OutputPolicyWhenDisabled
Definition at line 659 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE2_OUTNE0, MASK_MODE2_OUTNE1, OutputFalse, OutputHighImpedance, OutputTrue, read_8u(), REG_MODE2, and write_8u().
Referenced by setup().
void PCA9685::setLedAllCallAddressEnabled (bool argEnabled)
To set whether the device will answer to "Led All Call" address.
Parameters
argEnabled
true The device will answer;
false The device won't answer.
Definition at line 636 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_ALLCALL, read_8u(), REG_MODE1, and write_8u().
bool PCA9685::setOutput_const (uint8_t argOutputNbr, bool argEnabled)
To set argOutputNbr to be always ON/OFF depending on argEnabled.
Convenience function to quickly set on/off an output.
Internally calls PCA9685::setOutputForceFullOff() and PCA9685::setOutputForceFullOn().
Parameters
argOutputNbr The output to be configured.
Range: [0;PCA9685::OUTPUT_COUNT[.
argEnabled
true The output will be ON (no PWM);
false The output will be OFF (no PWM).
Returns
false If argOutputNbr is out of range;
true otherwise.
Definition at line 703 of file PCA9685.cpp.
References OUTPUT_COUNT, setOutputForceFullOff(), and setOutputForceFullOn().
Referenced by loop().
int8_t PCA9685::setOutput_pwm (uint8_t argOutputNbr, uint16_t argOn, uint16_t argOff)
To set the cycle & phase of an output.
Abstract from the datasheet:
The turn-on time of each LED driver output and the duty cycle of PWM can be controlled independently using the LEDn_ON and LEDn_OFF registers.
There will be two 12-bit registers per LED output. These registers will be programmed by the user. Both registers will hold a value from 0 to 4095. One 12-bit register will hold a value for the ON time and the other 12-bit register will hold the value for the OFF time. The ON and OFF times are compared with the value of a 12-bit counter that will be running continuously from 0000h to 0FFFh (0 to 4095 decimal).
The ON time, which is programmable, will be the time the LED output will be asserted and the OFF time, which is also programmable, will be the time when the LED output will be negated. In this way, the phase shift becomes completely programmable. The resolution for the phase shift is of the target frequency.
Parameters
argOutputNbr The output to control.
Range: [0;15]
argOn The value of the internal timer at which the output will be enabled.
Range: [0;4095].
argOff The value of the internal timer at which the output will be disabled.
Range: [0;4095].
Returns
-1 if argOutputNbr is beyound limits (equals or greater than PCA9685::OUTPUT_COUNT;
-2 if argOn is not included in a valid range;
-3 if argOff is not included in a valid range;
0 otherwise (no error detected).
Definition at line 749 of file PCA9685.cpp.
References OUTPUT_COUNT, REG_LED0_OFF_H, REG_LED0_OFF_L, REG_LED0_ON_H, REG_LED0_ON_L, and write_8u().
void PCA9685::setOutputChangeEvent (OutputChangeEvent argEvent)
To set the event type on which the output will be changed.
Parameters
argEvent The type of event.
See Also
PCA9685::OutputChangeEvent
Definition at line 781 of file PCA9685.cpp.
References ChangeOnStop, M_BIT_CLEAR, M_BIT_SET, MASK_MODE2_OCH, read_8u(), REG_MODE2, and write_8u().
bool PCA9685::setOutputForceFullOff (uint8_t argOutputNbr, bool argForceFullOff)
To enable/disable the forcing of output argOutputNbr to be always fully off.
When argForceFullOff is false, then the LEDn_ON registers for output argOutputNbr are used according to their normal definition; otherwise they'll be ignored and the output argOutputNbr will always be disabled.
Attention
Forcing an output to be full OFF overrides the forcing of full ON.
Note
When all LED outputs are configured as ‘always OFF’, the prescale counter and all associated PWM cycle timing logic are disabled.
Parameters
argOutputNbr The output number for which we want to set the "force full off" parameter.
Range: [0;15] / [0x00;0x0F].
argForceFullOff
true The output will always be disabled (no PWM)
false LEDn_ON and LEDn_OFF registers are used according to their normal definition.
Returns
false If argOutputNbr is out of range;
true otherwise.
Definition at line 820 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_LEDn_OFF_H_FULLOFF, OUTPUT_COUNT, read_8u(), REG_LED0_OFF_H, and write_8u().
Referenced by setOutput_const(), and setup().
bool PCA9685::setOutputForceFullOn (uint8_t argOutputNbr, bool argForceFullOn)
To enable/disable the forcing of output argOutputNbr to be always fully on.
When argForceFullOn is false, then the LEDn_ON and LEDn_OFF registers for output argOutputNbr are used according to their normal definition; otherwise they'll be ignored and the output argOutputNbr will always be enabled.
Warning
Forcing an output to be full ON is overridden by the forcing of full OFF.
Parameters
argOutputNbr The output number for which we want to set the "force full on" parameter.
Range: [0;15] / [0x00;0x0F].
argForceFullOn
true The output will always be enabled (no PWM)
false LEDn_ON and LEDn_OFF registers are used according to their normal definition.
Returns
false If argOutputNbr is out of range;
true otherwise.
Definition at line 863 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_LEDn_ON_H_FULLON, OUTPUT_COUNT, read_8u(), REG_LED0_ON_H, and write_8u().
Referenced by loop(), and setOutput_const().
bool PCA9685::setOutputFrequency (double argFrequency_Hz)
Calculates then sets internal counter's prescale value to let the output's frequency be as close as possible to argFrequency_Hz.
The outputs frequency depends on the internal counter's prescale value and its clock source's frequency.
This function calculates the reachable frequency range using PCA9685::clockFrequency(), checks if argFrequency_Hz is included in it, then calculates and sets the prescale value to be the closest to argFrequency_Hz.
Parameters
argFrequency_Hz The target output frequency.
Returns
true If argFrequency_Hz is in the reachable range;
false otherwise.
See Also
PCA9685::clockFrequency(), PCA9685::isUsingExternalClock(), PCA9685::outputPrescale()
Definition at line 919 of file PCA9685.cpp.
References clockFrequency(), DBG, setOutputPrescale(), and WARN.
Referenced by setup().
void PCA9685::setOutputPrescale (uint8_t argPrescale)
To set the value of the prescale that will be used to divide internal counter's input clock.
Parameters
argPrescale The new prescale value.
Range: [0x00;0xFF] / [0;255].
Definition at line 962 of file PCA9685.cpp.
References isSleeping(), REG_PRE_SCALE, setSleeping(), and write_8u().
Referenced by setOutputFrequency().
void PCA9685::setOutputStateInverted (bool argInverted)
To set wether the output's logical state is inverted or not. Applicable when /OE pin==0.
Parameters
argInverted
true The output's logical state will be inverted;
false The output's logical state will NOT be inverted.
Definition at line 986 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE2_INVRT, read_8u(), REG_MODE2, and write_8u().
void PCA9685::setOutputStructure (OutputStructure argStructure)
To set the output driver's internal structure type.
Parameters
argStructure The structure type.
See Also
PCA9685::OutputStructure
Definition at line 1008 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE2_OUTDRV, OutputStructureOpenDrain, read_8u(), REG_MODE2, and write_8u().
void PCA9685::setSleeping (bool argIsSleeping)
Sets the device's power mode.
When waking up the device (argIsSleeping==false) a delay of 500 microseconds is applied to avoid erroneous control registers readings.
Note
It takes the oscillator up to 500µs to be up and running when waking up. Timings on LEDn outputs are not guaranteed if PWM control registers are accessed within the 500 μs window.
Note
There is no start-up delay required when using the EXTCLK pin as the PWM clock.
Note
No PWM control is possible when the oscillator is off. When the oscillator is off (Sleep mode) the LEDn outputs cannot be turned on, off or dimmed/blinked.
Parameters
argIsSleeping
true Let the device go to sleep.
false Wake up the device.
Definition at line 1044 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_SLEEP, read_8u(), REG_MODE1, and write_8u().
Referenced by loop(), restart(), setOutputPrescale(), and setup().
void PCA9685::setSubAddress1Enabled (bool argEnabled)
Definition at line 1068 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_SUB1, read_8u(), REG_MODE1, and write_8u().
void PCA9685::setSubAddress2Enabled (bool argEnabled)
Definition at line 1084 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_SUB2, read_8u(), REG_MODE1, and write_8u().
void PCA9685::setSubAddress3Enabled (bool argEnabled)
Definition at line 1100 of file PCA9685.cpp.
References M_BIT_CLEAR, M_BIT_SET, MASK_MODE1_SUB3, read_8u(), REG_MODE1, and write_8u().
void PCA9685::setUseExternalClock (void)
To use an external clock source instead of the internal one.
Warning
the EXTCLK bit from MODE1 is a "sticky bit", it can ONLY be cleared by a power cycle or a software reset.
Definition at line 1122 of file PCA9685.cpp.
References M_BIT_SET, MASK_MODE1_EXTCLK, MASK_MODE1_SLEEP, read_8u(), REG_MODE1, and write_8u().
bool PCA9685::subAddress1Enabled (void)
Definition at line 1139 of file PCA9685.cpp.
References MASK_MODE1_SUB1, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), and setup().
bool PCA9685::subAddress2Enabled (void)
Definition at line 1147 of file PCA9685.cpp.
References MASK_MODE1_SUB2, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), and setup().
bool PCA9685::subAddress3Enabled (void)
Definition at line 1155 of file PCA9685.cpp.
References MASK_MODE1_SUB3, read_8u(), and REG_MODE1.
Referenced by pca9685_printConfig(), and setup().
void PCA9685::write_8u (const uint8_t & argAddress, const uint8_t & argData) protected
Convenience function to write a 8-bits unisgned argData into the register argAddress of the device at address PCA9685::m_address.
Parameters
argAddress The uint8_t register's address where we want to write.
argData The uint8_t data we want to write to argAddress register.
Definition at line 1170 of file PCA9685.cpp.
References m_address.
Referenced by restart(), setAutoIncrementRegister(), setDisabledOutputPolicy(), setLedAllCallAddressEnabled(), setOutput_pwm(), setOutputChangeEvent(), setOutputForceFullOff(), setOutputForceFullOn(), setOutputPrescale(), setOutputStateInverted(), setOutputStructure(), setSleeping(), setSubAddress1Enabled(), setSubAddress2Enabled(), setSubAddress3Enabled(), and setUseExternalClock().
Member Data Documentation
const uint8_t PCA9685::DEFAULT_ADDRESS = 0x40 static
The default address of the device when all bits [A0;A5] are set to logic 0.
Definition at line 50 of file PCA9685.h.
const float PCA9685::DEFAULT_CLOCKFREQUENCY_HZ = 25000000 static
The default clock frequency for internal counter. PCA9685's internal oscillator runs at 25MHz.
Definition at line 51 of file PCA9685.h.
const uint8_t PCA9685::m_address protected
The PCA9685's I2C slave address, as set by the constructor.
Definition at line 212 of file PCA9685.h.
Referenced by address(), read_8u(), and write_8u().
const double PCA9685::m_clockFrequency protected
The clock frequency, to calculate prescales; set by the constructor.
Definition at line 213 of file PCA9685.h.
Referenced by clockFrequency().
const uint8_t PCA9685::OUTPUT_COUNT = 16 static
The number of outputs the PCA9685 have.
Definition at line 52 of file PCA9685.h.
Referenced by loop(), pca9685_printConfig(), setOutput_const(), setOutput_pwm(), setOutputForceFullOff(), and setOutputForceFullOn().
The documentation for this class was generated from the following files:
PCA9685.h
PCA9685.cpp