ArduParts: DFRobotPowerShield Class Reference
DFRobotPowerShield Class Reference
Interface for DFRobot's Power Shield (SKU:DFR0105)
#include <DFRobotPowerShield.h>
Public Member Functions
DFRobotPowerShield ()
bool outputEnabled (void) const
DFRobotPowerShield::outputEnabled Returns the state of the auxiliary output as controlled by the PIN_AUXILIARYOUTPUT_CONTROL pin.
void setOutputEnabled (const bool &argEnabled)
DFRobotPowerShield::setOutputEnabled To set whether the auxiliary power output is enabled or not.
float voltage (void) const
DFRobotPowerShield::voltage.
void setVoltageRange (float argMin, float argMax)
DFRobotPowerShield::setVoltageRange To modify the voltage range measured by AN0; as the auxyliary output's voltage is measured through a pont diviseur de tension, the exact value may vary depending on the resistors. Use this method to adjust the min/max to best fit to the board.
Detailed Description
Interface for DFRobot's Power Shield (SKU:DFR0105)
See Also
http://www.dfrobot.com/wiki/index.php/Power_Shield_(SKU:DFR0105) for hardware details.
By default, the auxiliary ower output is disabled (see implementation of DFRobotPowerShield::init()).
Author
GOM
Copyright
© 2014 GOM
Date
2014-02-13 Thu. 15:25:16 Creation.
Definition at line 19 of file DFRobotPowerShield.h.
Constructor & Destructor Documentation
DFRobotPowerShield::DFRobotPowerShield ()
Definition at line 25 of file DFRobotPowerShield.cpp.
Member Function Documentation
bool DFRobotPowerShield::outputEnabled (void) const
DFRobotPowerShield::outputEnabled Returns the state of the auxiliary output as controlled by the PIN_AUXILIARYOUTPUT_CONTROL pin.
Returns
true if the output is enabled,
false otherwise.
Definition at line 57 of file DFRobotPowerShield.cpp.
References AUXILIARYOUTPUT_CONTROL_ON, and PIN_AUXILIARYOUTPUT_CONTROL.
Referenced by loop().
void DFRobotPowerShield::setOutputEnabled (const bool & argEnabled)
DFRobotPowerShield::setOutputEnabled To set whether the auxiliary power output is enabled or not.
Parameters
argEnabled The new state of the output (true=enabled, false=disabled).
Definition at line 79 of file DFRobotPowerShield.cpp.
References AUXILIARYOUTPUT_CONTROL_OFF, AUXILIARYOUTPUT_CONTROL_ON, and PIN_AUXILIARYOUTPUT_CONTROL.
Referenced by setup().
void DFRobotPowerShield::setVoltageRange (float argMin, float argMax)
DFRobotPowerShield::setVoltageRange To modify the voltage range measured by AN0; as the auxyliary output's voltage is measured through a pont diviseur de tension, the exact value may vary depending on the resistors. Use this method to adjust the min/max to best fit to the board.
Parameters
argMin The voltage of the auxiliary output when AN0 value is 0/1024.
argMax The voltage of the auxiliary output when AN0 value is 1024/1024.
Definition at line 100 of file DFRobotPowerShield.cpp.
float DFRobotPowerShield::voltage (void) const
DFRobotPowerShield::voltage.
Todo:
Check with diffenrent input voltages this function's output
Returns
Definition at line 114 of file DFRobotPowerShield.cpp.
References PIN_AUXILIARYOUTPUT_VOLTAGE.
Referenced by loop().
The documentation for this class was generated from the following files:
DFRobotPowerShield.h
DFRobotPowerShield.cpp