ArduParts: test_PCA9685.h File Reference
test_PCA9685.h File Reference
#include "Arduino.h"
Functions
void loop ()
void setup ()
Function Documentation
void loop ()
< ce return permet de sortir de la fonction loop; cette fonction etant integree dans une boucle infinie, elle sera immediatement rappelee.
< ce return permet de sortir de la fonction loop; cette fonction etant integree dans une boucle infinie, elle sera immediatement rappelee.
< ce return permet de sortir de la fonction loop; cette fonction etant integree dans une boucle infinie, elle sera immediatement rappelee.
Definition at line 54 of file test_Adafruit_BMP180.cpp.
References Mpu6050::accelX_g(), Mpu6050::accelY_g(), Mpu6050::accelZ_g(), Mpu6050::angleX_deg(), Mpu6050::angleY_deg(), Mpu6050::angleZ_deg(), Adafruit_BMP180::getAltitude_m(), Adafruit_BMP180::getPressure_Pa(), getSensorData(), Adafruit_BMP180::getTemperature_c(), Mpu6050::gyroX_deg_s(), Mpu6050::gyroY_deg_s(), Mpu6050::gyroZ_deg_s(), PCA9685::isSleeping(), LOG, LOGLN, PCA9685::OUTPUT_COUNT, DFRobotPowerShield::outputEnabled(), pca9685_printConfig(), Mpu6050::rawAccelX(), Mpu6050::rawAccelY(), Mpu6050::rawAccelZ(), Adafruit_BMP180::readRawPressure(), Adafruit_BMP180::readRawTemperature(), sensor, sensorPin, SERVOMAX, SERVOMIN, PCA9685::setOutput_const(), PCA9685::setOutputForceFullOn(), Adafruit_PWMServoDriver::setPWM(), PCA9685::setSleeping(), Mpu6050::temperature_celsius(), Mpu6050::updateData(), and DFRobotPowerShield::voltage().
void setup ()
Definition at line 33 of file test_Adafruit_BMP180.cpp.
References PCA9685::address(), Adafruit_PWMServoDriver::begin(), PCA9685::canRestart(), PCA9685::ChangeOnAcknowledge, PCA9685::ChangeOnStop, PCA9685::clockFrequency(), PCA9685::disabledOutputPolicy(), Mpu6050::init(), Adafruit_BMP180::init(), PCA9685::init(), PCA9685::isSleeping(), PCA9685::isUsingExternalClock(), PCA9685::ledAllCallAddressEnabled(), LOG, LOGLN, Adafruit_BMP180::NoError, PCA9685::outputChangeEvent(), PCA9685::OutputFalse, PCA9685::outputFrequency(), PCA9685::OutputHighImpedance, PCA9685::outputStateInverted(), PCA9685::outputStructure(), PCA9685::OutputStructureOpenDrain, PCA9685::OutputStructureTotemPole, PCA9685::OutputTrue, pca9685_printConfig(), PCA9685::reset(), PCA9685::restart(), PCA9685::setDisabledOutputPolicy(), DFRobotPowerShield::setOutputEnabled(), PCA9685::setOutputForceFullOff(), PCA9685::setOutputFrequency(), Adafruit_PWMServoDriver::setPWMFreq(), PCA9685::setSleeping(), PCA9685::subAddress1Enabled(), PCA9685::subAddress2Enabled(), PCA9685::subAddress3Enabled(), and Mpu6050::whoAmI().